# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Hydro Review
author: The Hydro Review
masthead_title:
minimal_mistakes_skin: default
favicon: "/assets/banners/favicon.png" # the favicon for your site
logo: &logo "/assets/banners/masthead.png"
og_image: "/assets/banners/favicon.png"
date_format: "%A, %B %-d, %Y"

# Build settings
markdown: kramdown
local_theme: minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/

search_provider: algolia
search: true

algolia:
  application_id: URBUGGX5IT # YOUR_APPLICATION_ID
  index_name:  thehydroreview-main # YOUR_INDEX_NAME
  search_only_api_key: ccf9435670096a7da16a58309e9a8ca9 # YOUR_SEARCH_ONLY_API_KEY
  powered_by: true

google:
  search_engine_id       : G-QZSRX88WM7
  instant_search         : true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - assets/originals
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
#  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-local-theme

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      show_date: true
      sidebar:
        nav: "years"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      image:
        twitter: *logo
      twitter:
        card: summary
      sidebar:
        nav: "years"

author:
  name   : "The Hydro Review"
  avatar : "/assets/banners/oklahoma-outline.png"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
